# -*- coding: utf-8 -*-
"""DataPreprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hm-i7wzYyeKXPwv9tQnkPh4VUmaq1OeD
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import ast

df=pd.read_csv('/content/drive/MyDrive/SearchEngineData/class-descriptions.csv')
df_annot=pd.read_csv('/content/drive/MyDrive/SearchEngineData/train-annotations-human-imagelabels.csv',usecols=['ImageID','LabelName', 'Confidence'])
df_img=pd.read_csv('/content/drive/MyDrive/SearchEngineData/train-images-with-labels-with-rotation.csv',usecols=['OriginalURL','ImageID','Author','Title'])

df_annot=df_annot[df_annot.Confidence==1]
df_annot_grb=df_annot.groupby('ImageID')['LabelName'].agg(list)

merged_df = pd.merge(df_img, new_annot, on='ImageID', how='inner')
merged_df.to_csv('/content/drive/MyDrive/SearchEngineData/merged_df_4M.csv')

new=pd.read_csv('/content/drive/MyDrive/SearchEngineData/data_4M.csv',converters={'LabelName': ast.literal_eval},index=False)

labels=df.set_index("/m/0100nhbf")["Sprenger's tulip"].to_dict()

new['Tags'] = new['LabelName'].apply(lambda x: [labels.get(label, label) for label in x])

new.drop(axis=1,columns='LabelName',inplace=True)

new.to_csv("/content/drive/MyDrive/SearchEngineData/final.csv")

final=pd.read_csv('/content/drive/MyDrive/SearchEngineData/final.csv',usecols=['ImageID','OriginalURL','Tags', 'Author','Title'])

final.head()

import requests

# Function to check if a URL is working
def is_url_working(url):
    try:
        response = requests.get(url)
        return response.status_code != 404
    except requests.exceptions.RequestException:
        return False

# Apply the function to the 'OriginalURL' column and filter the DataFrame
newa = newa[newa['OriginalURL'].apply(lambda x: is_url_working(x))]