version: '2'
services:    
  frontend:
    build: 
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
  fastapi:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    

 